#!/usr/bin/env python3
"""
Generate Weekly Opportunity Brief
"""

import json
from datetime import datetime
from pathlib import Path

def generate_brief():
    workspace = Path("/home/richard-laurits/.openclaw/workspace")
    radar_dir = workspace / "agents" / "opportunity-radar"
    
    # Load opportunities
    with open(radar_dir / "opportunities.json") as f:
        data = json.load(f)
    
    opportunities = data.get("opportunities", [])
    top_3 = opportunities[:3]
    
    # Build brief
    brief = f"""# Weekly Opportunity Brief
Generated: {datetime.now().strftime("%Y-%m-%d %H:%M CET")}
Period: Last 7 days  
Analysis: {len(opportunities)} opportunities detected

## Executive Summary

**System State:**
- Agents: 9 total, 1 active (11% utilization)
- Top Strategic Themes: Fantasy (75), Career (70), Health (70)
- Friction Point: Mass agent dormancy (highest drift score)
- Recovery Pattern: 1 successful (family communication)

**Opportunity Density:** HIGH
Multiple low-effort, high-impact moves available.

---

## Top 3 Actionable Opportunities

"""
    
    for i, opp in enumerate(top_3, 1):
        brief += f"""### {i}. {opp['title']}
**Theme:** {opp['theme'].replace('_', ' ').title()}  
**Leverage Score:** {opp['leverage_score']}/100  
**Effort:** {opp['estimated_effort']}  
**Risk:** {opp['risk_level']}

**Current State:**  
{opp['current_state']}

**Evidence:**
"""
        for ev in opp['evidence']:
            brief += f"- {ev}  \n"
        
        brief += f"""
**Expected ROI:**  
{opp['expected_roi']}

**Recommended Action:**  
```bash
{opp['recommended_action']}
```

---

"""
    
    # Strategic context
    brief += f"""## Strategic Context

**Priority Alignment Check:**
- ✅ Fantasy & Career: Well-resourced (expanded hours)
- ⚠️ Health: High priority, low automation (manual-only)
- ⚠️ Language: High priority, disabled agent
- ⚠️ Family: Only recovery was here (fragile)

**Key Insight:**  
System has **high capability** (9 specialized agents) but **low activation** (11% running). 
The infrastructure exists—opportunity is in unlocking it.

---

## Decision Matrix

| Move | Effort | Impact | Risk | Do First? |
|------|--------|--------|------|-----------|
"""
    
    for opp in opportunities:
        impact = "High" if opp['leverage_score'] >= 80 else "Medium" if opp['leverage_score'] >= 60 else "Low"
        do_first = "✅" if opp in top_3 else ""
        brief += f"| {opp['title'][:25]}... | {opp['estimated_effort'].split(' - ')[0]} | {impact} | {opp['risk_level']} | {do_first} |\n"
    
    brief += f"""
---

## Recommended Sequence

**Week 1:**
1. Enable Health Agent auto-mode (15 min, immediate ROI)
2. Add smart_scheduler to HEARTBEAT.md (30 min, unlocks 60% of agents)

**Week 2:**
3. Activate French Tutor (15 min, daily value)
4. Add Jan greeting backup trigger (15 min, relationship protection)

**Total Time:** ~75 minutes  
**Expected Value:** 5-6 hours/week automation gains

---

*Generated by Opportunity Radar Agent*  
*All opportunities evidence-based from system data*
"""
    
    with open(radar_dir / "WEEKLY_OPPORTUNITY_BRIEF.md", "w") as f:
        f.write(brief)
    
    print("✅ WEEKLY_OPPORTUNITY_BRIEF.md generated")
    print(f"\nTop 3 opportunities highlighted")
    return brief

if __name__ == "__main__":
    generate_brief()
